# -----------------------------
# Server 設定不需重複寫 context-path
# Docker 仍會套用 application.yml 的 /api
# -----------------------------
server:
  port: 8080

# -----------------------------
# Redis 使用 Docker 環境變數
# -----------------------------
spring:
  config:
    import: optional:file:.env[.properties]
  data:
    redis:
      host: redis
      port: 6379
      password: 1234
      database: 0
      timeout: 2000

  # Datasource 使用 Docker 環境變數
  datasource:
    url: jdbc:postgresql://db:5432/interviewworks?currentSchema=interviewworks_schema
    username: postgres
    password: 1234
